# Generated by Django 6.0.5 on 2026-05-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_injured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='minutes_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
